<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CS2103/T Website - Error Handling: Exceptions</title>
    <link rel="stylesheet" href="..\..\..\markbind\css\bootstrap.min.css">
    <link rel="stylesheet" href="..\..\..\markbind\css\github.min.css">
    <link rel="stylesheet" href="..\..\..\markbind\css\markbind.css">
    <link rel="icon" href="/website-base/favicon.ico">
</head>
<body>
<div id="app" class="container-fluid">
    <div>
  <link rel="stylesheet" href="/website-base/book/css/textbook.css">
  <div class="website-content" id="all">
    <p><span class="dimmed"><strong><span>Implementation â†’ Error Handling â†’
</span></strong>
      </span>
    </p>
    <div id="title">
      <div>
        <h2 id="exceptions">Exceptions</h2>
      </div>
    </div>
    <div id="main">
      <div>
        <div>
          <panel type="seamless" expanded="">
            <span slot="header" class="panel-title"><div>
<h4 id="what">What</h4></div></span>
            <div>
              <p><strong>Exceptions are used to deal with <em>'unusual' but not entirely unexpected</em> situations</strong> that the program might encounter at run time.</p>
              <tip-box type="definition">
                <div>
                  <p><strong>Exception</strong>:</p>
                  <blockquote>
                    <p>An <em>exception</em> is an event, which occurs during the execution of a program, that disrupts the normal flow of the program's instructions. â€“- Java Tutorial (Oracle Inc.)</p>
                  </blockquote>
                </div>
              </tip-box>
              <tip-box>
                <p>ðŸ“¦ Examples:</p>
                <ul>
                  <li>A network connection encounters a timeout due to a slow server.</li>
                  <li>The code tries to read a file from the hard disk but the file is corrupted and cannot be read.</li>
                </ul>
              </tip-box>
            </div>
          </panel>
        </div>
        <div>
          <panel type="seamless" expanded="">
            <span slot="header" class="panel-title"><div>
<h4 id="how">How</h4></div></span>
            <div>
              <p><strong>Most languages allow a method/function to encapsulate the unusual situation in an Exception object and 'throw'/'raise' that object so that another piece of code can 'catch' it and deal with it.</strong> This is especially useful
                when code segment that encountered the unusual situation does not know how to deal with it.</p>
              <p><strong>Exception objects can propagate up the function call hierarchy until it is dealt with.</strong> Usually, an exception thrown by a function is caught by the caller function. If the called function does not know how to deal with the
                exception it caught, it can throw/raise the Exception object to its own caller. If none of the callers is prepared to deal with the exception, the exceptions can propagate through the
                <tooltip content="the hieararchy of function calls">function call stack</tooltip> until it is received by the main function and thrown to the runtime, thus halting the system.</p>
              <tip-box>
                <tabs>
                
                  <tab header="Java">
                    <p>ðŸ“¦ In the code given below, <code>processArray</code> can potentially throw an <code>InvalidInputException</code>. Because of that, <code>processInput</code> method invokes <code>processArray</code> method inside a <code>try{ }</code>                      block and has a <code>catch{ }</code> block to specify what to do if the exception is actually thrown.</p>
                    <img src="/website-base/book/errorHandling/exceptions/how/images/processInput.png" width="400">
                    <p></p>
                    <p></p>
                  </tab>
                
                  <tab header="Python">
                    <p>ðŸ“¦ In the code given below, <code>process_array</code> function can potentially raise a <code>ValueError</code> exception. Because of that, <code>process_input</code> function invokes <code>process_array</code> function inside a <code>try</code>                      clause and has a <code>except</code> clause to specify what to do if the exception is actually raised.</p>
                    <img src="/website-base/book/errorHandling/exceptions/how/images/example-python.png" width="400">
                    <p></p>
                  </tab>
                </tabs>
                <hr>
              </tip-box>
              <p>Advantages of exception handling in this way:</p>
              <ul>
                <li>The ability to propagate error information through the call stack.</li>
                <li>The separation of code that deals with 'unusual' situations from the code that does the 'usual' work.</li>
              </ul>
            </div>
          </panel>
        </div>
        <div>
          <panel type="seamless" expanded="">
            <span slot="header" class="panel-title"><div>
<h4 id="when">When</h4></div></span>
            <div>
              <p>In general, use exceptions only for 'unusual' conditions. Use normal <code>return</code> statements to pass control to the caller for conditions that are 'normal'.</p>
            </div>
          </panel>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</body>
<script src="..\..\..\markbind\js\vue.min.js"></script>
<script src="..\..\..\markbind\js\vue-strap.min.js"></script>
<script>
    const baseUrl = '/website-base'
</script>
<script src="..\..\..\markbind\js\setup.js"></script>
</html>
